name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Run Python tests
        run: |
          python -m pytest test_app.py -v

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: infra-alerting-dashboard/package-lock.json
          
      - name: Install Node.js dependencies
        working-directory: infra-alerting-dashboard
        run: npm ci
        
      - name: Run React tests
        working-directory: infra-alerting-dashboard
        run: npm test -- --watchAll=false
        
      - name: Build React app
        working-directory: infra-alerting-dashboard
        run: npm run build

  build-docker:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: traffic-dashboard-backend:latest
          
      - name: Build Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./infra-alerting-dashboard
          file: ./infra-alerting-dashboard/Dockerfile
          push: false
          tags: traffic-dashboard-frontend:latest 